name: Request a feature for your Valetudo Vacuum Camera
description: Request a feature for your Valetudo Vacuum Camera
labels: enhancement
assignees: 'SCA075'
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for feature requests or enhancements only!

        If you have a bug or a question, please use the dedicated form.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: >-
        A clear and concise description of what should change[...]
  - type: textarea
    validations:
      required: true
    attributes:
      label: Solution
      description: >-
        A clear and concise description of what you want to happen.
  - type: textarea
    validations:
      required: false
    attributes:
      label: Alternatives
      description: >-
        A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    validations:
      required: false
    attributes:
      label: Context
      description: >-
        Add any other context about the feature request here.