---
reload:
  name: Reload
  description: Reload all entities of MQTT Vacuum Camera platform

turn_off:
  target:
    entity:
      domain: camera

turn_on:
  target:
    entity:
      domain: camera

snapshot:
  target:
    entity:
      domain: camera
  fields:
    filename:
      required: true
      example: "config/www/snapshot_.png"
      selector:
        text:

reset_trims:

obstacle_view:
  name: Obstacle view
  description: Select the coordinates to Show the obstacle on the map.
  target:
    entity:
      domain: camera
  fields:
    coordinates_x:
      name: x
      description: Coordinate x for the obstacle view.
      required: true
      selector:
        number:
            min: 0
            max: 90000
    coordinates_y:
      name: y
      description: Coordinate y for the obstacle view.
      required: true
      selector:
          number:
              min: 0
              max: 90000

vacuum_go_to:
  name: Vacuum go to
  description: Go to the specified coordinates
  target:
    entity:
      integration: mqtt
      domain: vacuum
  fields:
    x_coord:
      name: X coordinate
      description: x-coordinate
      required: true
      example: 26300
      selector:
        text:
    y_coord:
      name: Y coordinate
      description: y-coordinate
      required: true
      example: 22500
      selector:
        text:
    spot_id:
      name: Spot Id
      description: Rand256 pre-defined point.
      required: false
      example: "Somewhere"
      selector:
        text:

vacuum_clean_zone:
  name: Vacuum clean zone
  description: Start the cleaning operation in the selected areas for the number of repeats indicated.
  target:
    entity:
      integration: mqtt
      domain: vacuum
  fields:
    zone:
      name: Zone
      description: Optional Array of zones. Each zone is an array of 4 integer values.
      required: false
      example: "[[23510,25311,25110,26362]]"
      selector:
        object:
    zone_ids:
      name:  Zone Ids
      description: Optional Rand256 predefined zone_ids (array of strings).
      required: false
      example: "[\"Bar\", \"Trash Can\"]"
      selector:
        object:
    repeats:
      name: Repeats
      description: Optional Number of cleaning (default 1) repeats for each zone (max 3).
      selector:
        number:
          min: 1
          max: 3

vacuum_clean_segments:
  name: Vacuum clean segment
  description: Start cleaning of the specified segment(s).
  target:
    entity:
      integration: mqtt
      domain: vacuum
  fields:
    segments:
      name: Segments
      description: Segments.
      required: true
      example: "[1,2]"
      selector:
        object:
    repeats:
      name: Repeats
      description: Number of cleaning repeats for each segment.
      selector:
        number:
          min: 1
          max: 3

vacuum_map_save:
  name: Vacuum map save
  description: Save the current map.
  target:
    entity:
      integration: mqtt
      domain: vacuum
  fields:
    map_name:
      name: Map name
      description: Name of the map to save.
      required: true
      example: "My map"
      selector:
        text:

vacuum_map_load:
  name: Vacuum map load
  description: Load the specified map.
  target:
    entity:
      integration: mqtt
      domain: vacuum
  fields:
    map_name:
      name: Map name
      description: Name of the map to load.
      required: true
      example: "My map"
      selector:
        text:
